### ISSUE TITLE
How access the `type`'s module?

### ISSUE THREAD

**Issue by chukinas** [ejpcmac/typed_struct#21]
I'm trying to write a plugin that does the following for each field:
- extract the module from the type
- call a function from that module

The problem arises when the type makes use of an alias. Here's a little example:

```elixir
defmodule MyModule do
  alias MyModule.Collection
  use TypedStruct
  typedstruct do
    field :my_field, Collection.t
  end
end
```

Let's say there's a function MyModule.Collection.my_function/0. I want to call that function inside a plugin's `field` callback. But I'm twisting myself into knots trying to get it to happen, but it ought to be really easy. Here's a small self-contained example of what I'm trying to accomplish:

```elixir
defmodule LuckyLeopard.Dependency do
  @type t :: 42
  def get_meaning_of_life, do: 42
end

defmodule LuckyLeopard.MeaningOfLifePlugin do
  defmacro create_fn_meaning_of_life(return_type) do
    quote do
      @spec get_meaning_of_life :: unquote(return_type)
      defdelegate get_meaning_of_life, to: unquote(extract_type_module(return_type))
    end
  end

  defp extract_type_module(type_ast) do
    {_type_ast, alias_ast} =
      Macro.prewalk(type_ast, nil, fn
        {:__aliases__, _meta, _list} = alias_ast, nil ->
          {alias_ast, alias_ast}
        ast, acc ->
          {ast, acc}
      end)
    alias_ast
  end
end

defmodule LuckyLeopard do
  alias LuckyLeopard.Dependency
  import LuckyLeopard.MeaningOfLifePlugin
  create_fn_meaning_of_life(Dependency.t)
end
```

Am I missing something? I'm open to ideas, but it's striking that you use function callbacks instead of macros. Also, that there's that anonymous function to "prevent leaks". I kinda want those leaks, but I'm sure there was  a reason you did it that way.

**Comment by chukinas** [comment]
And actually, I think there's probably a bug to be dealt with first. This could give us the opportunity to kill two birds with one stone.

Given this simple example:

```elixir
defmodule ClassyCrab.Dependency do
  @type t :: 42
end

defmodule ClassyCrab do
  alias ClassyCrab.Dependency
  use TypedStruct
  typedstruct do
    alias ClassyCrab.Dependency, as: DependencyAlias # warning: `unused alias DependencyAlias`
    field :first, Dependency.t
    field :second, DependencyAlias.t
  end
end
```

Then do this in `IEx`: 

```
iex(1)> t OrbitalOrca
@type t() :: %OrbitalOrca{
        first: OrbitalOrca.Dependency.t() | nil,
        second: DependencyAlias.t() | nil
      }
```

Note how the `:first` type translates correctly, but `:second` does not.

Are you open to a PR?

**Comment by chukinas** [comment]
btw, TypedStruct is one of my absolute favorite libraries. Simple. Elegant. I use it in every project. Just wanted to make sure I got that out there!

**Comment by ejpcmac** [comment]
Hello @jonathanchukinas, regarding your second message: this is indeed a bug. Thank you for reporting it!

Removing the anonymous function solves it. I had originally put this to avoid the `field` macro to be available outside of the `typedstruct` block, which would be obviously not semantically correct. This is a behaviour I was actually able to see at the time, and I’ve even written a test to ensure it was not possible to do so. The test is now passing without the anonymous function, so I assume I had fixed in `typed_struct` a bug that was in fact a soundness bug in Elixir itself. I haven’t (yet) been able to reproduce it on old Elixir versions, so it may have been only an issue on a very specific Elixir version. Anyway, even if still needed, the span of this anonymous function should have included the whole quoted block I think.

You can indeed open a PR with the fix, on the `develop` branch, or I can also do it tomorrow, as you want.

Does this solve your first issue also? I won’t have the time to understand your need tonight, since new year’s eve is starting soon here in Europe, but will review it later in the week-end.

Regarding why I am using function callbacks instead of macro callbacks: while the `init` macro callback is called directly from the `plugin` macro, `field` and `after_definition` need to be called in loops in the field definitions and after the type definition. If defined as macros, they would insert their code inside the scope of the loop. Defined functions, for instance, would not be accessible outside of this (internal) scope. By defining them as functions that return a quoted block, I am able to actually insert the code in the module directly by calling `Module.eval_quoted/2`. If you find however a more elegant way to do this, I’m ready to accept it :)

I’ll release the fix while pushing `typed_struct` to 1.0.0, since I think it’s time for it now. It’s been pretty stable for the last 1.5 years, and except if your first need reveals some needs in API changes, I think it’s good to stabilise it for real.

**Comment by chukinas** [comment]
@ejpcmac  You're right about removing the anonymous function - it fixes the bug and doesn't break any tests, so that's a great place to start.

But by itself, it doesn't fix my original problem, so I might recommend not advancing to `1.0.0` just yet.

I've almost got a workable solution to share with you. More details to come, but I just wanted to touch base first.

**Comment by chukinas** [comment]
Here's a trick I picked up along the way (maybe Chris McCord's metaprogramming book?) for enforcing that certain macros only be called within the do blocks of other macros:

```elixir
defmodule GrumblingGuppy.Macros do

  defmacro primary_macro(do: block) do
    quote do
      IO.puts "\nCalling `outer_macro/0`"
      @ts_in_progress true
      unquote(block)
      Module.delete_attribute(__MODULE__, :ts_in_progress)
    end
  end

  defmacro inner_macro do
    quote do
      if !Module.get_attribute(__MODULE__, :ts_in_progress) do
        raise(CompileError, description: "Naughty naughty - You're not allowed to call `inner_macro/0` outside of a `primary_macro/1` block!")
      end
      IO.puts "\nCalling `inner_macro/0`"
    end
  end

end

defmodule GrumblingGuppy do
  import GrumblingGuppy.Macros
  primary_macro do
    inner_macro()
  end
  # unquoting the following will raise an exception
  # inner_macro()
end
```

**Comment by chukinas** [comment]
So anyway, that's one way to ensure that `field` and `plugin` are always called inside a `typedstruct` block. It can also be used to ensure that there are no nested typedstruct calls.

The harder problem to solve is this: How to prevent `init` imports from leaking into the broader context. But instead of trying to solve that issue, I'd like to challenge you to remove that design requirement. As I mentioned in the first post, I think "leaking" is actually a good thing here, for a couple reasons.
1. There's already a lot of "leaking" going on. For example, I can (and do) use `field` to inject new functions into the caller module.
2. It's true that responsible metaprogramming involves injecting as little as possible into the caller's context. But it the macro author (i.e., me) has a good reason to inject e.g. an import inside of `init`, then why shouldn't I be allowed to do it? Shouldn't the onus be on the macro author to write good code? Why should typedstruct take on this responsibility?

Very curious to hear your thoughts. Happy new year!

**Comment by jonathanchukinas** [comment]
@ejpcmac so after a good amount of research, I see you're totally right to create a lexical scope inside a `typedstruct` block. I'm not looking to change that.

I did find a way to loop over the plugin callbacks without using `Module.eval_quoted`. I'd like to create a PR that includes this change as well as a proposed feature: adding the current `Macro.Env` as a fourth param to the `field` callback. 

I'm struggling with the workflow though and maybe you can help me? It seems to be an issue with the git flow:
![image](https://user-images.githubusercontent.com/50892128/150388043-8573767c-ff9d-4e90-9d35-e6a332b43587.png)

**Comment by ejpcmac** [comment]
TypedStruct 0.3.0 has been released on [hex.pm](https://hex.pm/packages/typed_struct) :tada:
